# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
name = "O n치s"
url = "#about"
weight = 1

[[main]]
name = "Publik치cie"
url = "#publications"
weight = 3

[[main]]
name = "Projekty"
url = "#projects"
weight = 4


[[main]]
name = "Blog"
url = "#posts"
weight = 2


[[main]]
name = "Predn치코ky"
url = "/talk/"
weight = 8

[[main]]
name = "Kontakt"
url = "#contact"
weight = 10
